In [2]:
import math
import numpy as np
print("hello world")
a = 12;

hello world


In [3]:
print(a+12)

print(math.pi)
# 创建一维数组
a = np.array([1, 2, 3])
print("一维数组a:", a)

# 创建二维数组
b = np.array([[1, 2], [3, 4]])
print("二维数组b:\n", b)

# 数组的常用属性
print("数组a的维度:", a.ndim)
print("数组b的形状:", b.shape)
print("数组a的元素个数:", a.size)
print("数组b的数据类型:", b.dtype)

# 特殊数组创建
c = np.zeros((2, 3))  # 全零数组
d = np.ones((3, 2))   # 全一数组
e = np.eye(3)         # 单位矩阵
print("全零数组c:\n", c)
print("全一数组d:\n", d)
print("单位矩阵e:\n", e)

# 数组操作
f = np.arange(0, 10, 2)  # 类似range，生成等差数列
g = np.linspace(0, 10, 5)  # 生成指定数量的等分数列
print("arange生成f:", f)
print("linspace生成g:", g)

# 数组运算
h = a + 2
i = a * 2
j = a ** 2
k = np.sin(a)
print("数组运算：")
print("a+2:", h)
print("a*2:", i)
print("a^2:", j)
print("sin(a):", k)

# 矩阵乘法
l = np.dot(b, b.T)  # 矩阵与转置矩阵相乘
print("矩阵b与其转置的乘积:\n", l)

# 随机数生成
m = np.random.rand(2, 3)  # 生成[0,1)区间内的随机数组
n = np.random.randn(2, 3)  # 生成正态分布的随机数组
print("随机数组m:\n", m)
print("正态分布数组n:\n", n)

# 统计运算
o = np.array([[1, 2], [3, 4]])
print("数组o的求和:", np.sum(o))
print("数组o按列求和:", np.sum(o, axis=0))
print("数组o按行求和:", np.sum(o, axis=1))
print("数组o的平均值:", np.mean(o))
print("数组o的最小值:", np.min(o))
print("数组o的最大值:", np.max(o))


24
3.141592653589793
一维数组a: [1 2 3]
二维数组b:
 [[1 2]
 [3 4]]
数组a的维度: 1
数组b的形状: (2, 2)
数组a的元素个数: 3
数组b的数据类型: int32
全零数组c:
 [[0. 0. 0.]
 [0. 0. 0.]]
全一数组d:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
单位矩阵e:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange生成f: [0 2 4 6 8]
linspace生成g: [ 0.   2.5  5.   7.5 10. ]
数组运算：
a+2: [3 4 5]
a*2: [2 4 6]
a^2: [1 4 9]
sin(a): [0.84147098 0.90929743 0.14112001]
矩阵b与其转置的乘积:
 [[ 5 11]
 [11 25]]
随机数组m:
 [[0.87097237 0.98763965 0.25641602]
 [0.01940616 0.83253396 0.01345435]]
正态分布数组n:
 [[-0.3157346   0.74962735 -0.21970771]
 [-0.79631953  2.02804422 -1.01230374]]
数组o的求和: 10
数组o按列求和: [4 6]
数组o按行求和: [3 7]
数组o的平均值: 2.5
数组o的最小值: 1
数组o的最大值: 4
